// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeExtractorAPI.DataAccess.Context;

#nullable disable

namespace ResumeExtractorAPI.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227072244_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeResultId");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredentialID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CredentialURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResumeResultId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Education", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeResultId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proficiency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResumeResultId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.PersonalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GitHub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResumeResultId")
                        .IsUnique();

                    b.ToTable("PersonalInfos");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technologies")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeResultId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Objective")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResumeResults");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCurrentlyWorkingHere")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResumeResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StartDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeResultId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Award", b =>
                {
                    b.HasOne("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", "ResumeResult")
                        .WithMany("Awards")
                        .HasForeignKey("ResumeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeResult");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Certification", b =>
                {
                    b.HasOne("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", "ResumeResult")
                        .WithMany("Certifications")
                        .HasForeignKey("ResumeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeResult");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Education", b =>
                {
                    b.HasOne("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", "ResumeResult")
                        .WithMany("Education")
                        .HasForeignKey("ResumeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeResult");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Language", b =>
                {
                    b.HasOne("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", "ResumeResult")
                        .WithMany("Languages")
                        .HasForeignKey("ResumeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeResult");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.PersonalInfo", b =>
                {
                    b.HasOne("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", "ResumeResult")
                        .WithOne("PersonalInfo")
                        .HasForeignKey("ResumeExtractorAPI.DataAccess.Entities.PersonalInfo", "ResumeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeResult");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.Project", b =>
                {
                    b.HasOne("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", "ResumeResult")
                        .WithMany("Projects")
                        .HasForeignKey("ResumeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeResult");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.WorkExperience", b =>
                {
                    b.HasOne("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", "ResumeResult")
                        .WithMany("WorkExperience")
                        .HasForeignKey("ResumeResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResumeResult");
                });

            modelBuilder.Entity("ResumeExtractorAPI.DataAccess.Entities.ResumeResult", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Certifications");

                    b.Navigation("Education");

                    b.Navigation("Languages");

                    b.Navigation("PersonalInfo");

                    b.Navigation("Projects");

                    b.Navigation("WorkExperience");
                });
#pragma warning restore 612, 618
        }
    }
}
